.\"
.\" Copyright (c) 2020-2021 aabacchus
.\"
.Dd November 2020
.Dt bitratePlotter 1 "November 2020" "v0.1.1"
.Os
.Sh NAME
.Nm bitratePlotter
.Nd create a graph of bitrate over duration
.Sh SYNOPSIS
.Nm
.Ar
.Sh DESCRIPTION
.Pp
.Nm
uses \f[I]matplotlib\f[R] and
\f[I]ffmpeg_bitrate_stats\f[R] (which itself uses FFmpeg) to create
graphs plotting the bitrate of a video or audio file (or files) against
the duration of the clip.
Such graphs can be interesting when considering various types of
compression, in particular the CRF factor in codecs x264, x265, and
libvpx.
Running
.Nm
without any input files gives a prompt for an input file.
.Sh COPYRIGHT
.Pp
This software is released under the MIT license, of which you should
have received a copy along with the software.
.Sh MORE
.Pp
See the program\[cq]s repository on
.Lk https://www.github.com/aabacchus/bitratePlotter Github
.Sh AUTHORS
.An aabacchus
.Aq Mt ben@bvnf.space
